site_name: SYW's Computer Science Portfolio # 网站标题
site_description: "A personal blog documenting my computer science journey."
site_author: "SYW"

theme:
    name: material # 使用 Material 主题
    features:
      - navigation.tabs
      - navigation.sections
      - search.suggest
      - search.highlight
      - content.code.copy
    font:
      text: Roboto
      code: Roboto Mono
    logo: assets/logo.jpg # 网站 logo
    favicon: assets/favicon.ico # 网站 favicon
    palette:
        # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: blue
      accent: deep orange

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wys917

nav:
  - Home: index.md
  - Algorithms:
    - 01-Algorithms/index.md
    - 'Problem Solutions':
      - 'LeetCode 101: Symmetric Tree': 01-Algorithms/题目与解法汇总/leetcode-101-对称二叉树.md
      - 'LeetCode 102: Binary Tree Level Order Traversal': 01-Algorithms/题目与解法汇总/leetcode-102-二叉树的层序遍历.md
      - 'LeetCode 141: Linked List Cycle': 01-Algorithms/题目与解法汇总/leetcode-141-环形链表.md
      - 'LeetCode 206: Reverse Linked List': 01-Algorithms/题目与解法汇总/leetcode-206-反转链表.md
      - 'LeetCode 21: Merge Two Sorted Lists': 01-Algorithms/题目与解法汇总/leetcode-21-合并两个有序链表.md
      - 'LeetCode 230: Kth Smallest Element in a BST': 01-Algorithms/题目与解法汇总/leetcode-230-二叉搜索树中第K小的元素.md
      - 'LeetCode 283: Move Zeroes': 01-Algorithms/题目与解法汇总/leetcode-283-移动零.md
      - 'LeetCode 3: Longest Substring Without Repeating Characters': 01-Algorithms/题目与解法汇总/leetcode-3-无重复字符串的最长子串.md
      - 'LeetCode 49: Group Anagrams': 01-Algorithms/题目与解法汇总/leetcode-49-字母异位词分组.md
      - 'LeetCode 94: Binary Tree Inorder Traversal': 01-Algorithms/题目与解法汇总/leetcode-94-二叉树的中序遍历.md
      - 'LeetCode 98: Validate Binary Search Tree': 01-Algorithms/题目与解法汇总/leetcode-98-验证二叉搜索树.md
      - 'Hash Table Summary': 01-Algorithms/题目与解法汇总/leetcode-哈希表专题.md
  - HPC:
    - 'MiniCluster搭建及HPL测试': 02-HPC/迷你计算集群搭建及HPL性能测试/迷你计算集群搭建及HPL性能测试.md
    - 'MiniCluster实验反思': 02-HPC/迷你计算集群搭建及HPL性能测试/reflection.md
    - 'MPI+OpenMP混合并行BiCGSTAB': 02-HPC/基于MPI+OpenMP混合并行的BiCGSTAB算法实现与调优/README.md
    - 'AVX-512矩阵乘法优化': 02-HPC/基于AVX-512的整数量化矩阵乘法优化/基于AVX-512的整数量化矩阵乘法优化.md
  - Notes and Thoughts:
    - 'Git Workflow': 03-Notes-and-Thoughts/git的工作流.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
